import { writable } from 'svelte/store';

export const mapConfig = writable({
  "title": "What is the relationship between income and mammography screening in the EU? ",
  "subtitle": "In 2019, women in the EU's highest income bracket were 4.9 percentage points more likely than those in the lowest to report that their last mammogram was one or two years ago.  Bulgaria had the largest positive gap (21.2%), while Croatia had the largest negative gap (-12.5%).",
  "colourSchemeClasses": 7,
  "data": "country,id,value,extraInfo,text_content,link_text,link_url_target,audio_url_1,audio_url_2,audio_url_3,image_url_source,image_url_target,video_url\nBelgium,BE,-0.076,false,-7.6 percentage points,,,,,,,,\nBulgaria,BG,0.212,false,+21.2 percentage points,,,,,,,,\nCzechia,CZ,0.065,false,+6.5 percentage points,,,,,,,,\nDenmark,DK,-0.016,false,-1.6 percentage points,,,,,,,,\nGermany,DE,0.076,false,+7.6 percentage points,,,,,,,,\nEstonia,EE,0.059,false,+5.9 percentage points,,,,,,,,\nIreland,IE,-0.085,false,-8.5 percentage points,,,,,,,,\nGreece,EL,-0.017,false,-1.7 percentage points,,,,,,,,\nSpain,ES,-0.023,false,-2.3 percentage points,,,,,,,,\nFrance,FR,0.027,false,+2.7 percentage points,,,,,,,,\nCroatia,HR,-0.125,false,-12.5 percentage points,,,,,,,,\nItaly,IT,0.053,false,+5.3 percentage points,,,,,,,,\nCyprus,CY,0.117,false,+11.7 percentage points,,,,,,,,\nLatvia,LV,0.008,false,+0.8 percentage points,,,,,,,,\nLithuania,LT,0.092,false,+9.2 percentage points,,,,,,,,\nLuxembourg,LU,-0.018,false,-1.8 percentage points,,,,,,,,\nHungary,HU,0.019,false,+1.9 percentage points,,,,,,,,\nMalta,MT,0.001,false,+0.1 percentage points,,,,,,,,\nNetherlands,NL,-0.008,false,-0.8 percentage points,,,,,,,,\nAustria,AT,0.045,false,+4.5 percentage points,,,,,,,,\nPoland,PL,0.069,false,+6.9 percentage points,,,,,,,,\nPortugal,PT,-0.047,false,-4.7 percentage points,,,,,,,,\nRomania,RO,0.116,false,+11.6 percentage points,,,,,,,,\nSlovenia,SI,0.050,false,+5.0 percentage points,,,,,,,,\nSlovakia,SK,0.107,false,+10.7 percentage points,,,,,,,,\nFinland,FI,-0.010,false,-1.0 percentage points,,,,,,,,\nSweden,SE,-0.042,false,-4.2 percentage points,,,,,,,,",
  "parsedData": [
    {
      "country": "Belgium",
      "id": "BE",
      "value": -0.076,
      "extraInfo": false,
      "text_content": "-7.6 percentage points",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Bulgaria",
      "id": "BG",
      "value": 0.212,
      "extraInfo": false,
      "text_content": "+21.2 percentage points",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Czechia",
      "id": "CZ",
      "value": 0.065,
      "extraInfo": false,
      "text_content": "+6.5 percentage points",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Denmark",
      "id": "DK",
      "value": -0.016,
      "extraInfo": false,
      "text_content": "-1.6 percentage points",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Germany",
      "id": "DE",
      "value": 0.076,
      "extraInfo": false,
      "text_content": "+7.6 percentage points",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Estonia",
      "id": "EE",
      "value": 0.059,
      "extraInfo": false,
      "text_content": "+5.9 percentage points",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Ireland",
      "id": "IE",
      "value": -0.085,
      "extraInfo": false,
      "text_content": "-8.5 percentage points",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Greece",
      "id": "EL",
      "value": -0.017,
      "extraInfo": false,
      "text_content": "-1.7 percentage points",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Spain",
      "id": "ES",
      "value": -0.023,
      "extraInfo": false,
      "text_content": "-2.3 percentage points",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "France",
      "id": "FR",
      "value": 0.027,
      "extraInfo": false,
      "text_content": "+2.7 percentage points",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Croatia",
      "id": "HR",
      "value": -0.125,
      "extraInfo": false,
      "text_content": "-12.5 percentage points",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Italy",
      "id": "IT",
      "value": 0.053,
      "extraInfo": false,
      "text_content": "+5.3 percentage points",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Cyprus",
      "id": "CY",
      "value": 0.117,
      "extraInfo": false,
      "text_content": "+11.7 percentage points",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Latvia",
      "id": "LV",
      "value": 0.008,
      "extraInfo": false,
      "text_content": "+0.8 percentage points",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Lithuania",
      "id": "LT",
      "value": 0.092,
      "extraInfo": false,
      "text_content": "+9.2 percentage points",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Luxembourg",
      "id": "LU",
      "value": -0.018,
      "extraInfo": false,
      "text_content": "-1.8 percentage points",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Hungary",
      "id": "HU",
      "value": 0.019,
      "extraInfo": false,
      "text_content": "+1.9 percentage points",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Malta",
      "id": "MT",
      "value": 0.001,
      "extraInfo": false,
      "text_content": "+0.1 percentage points",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Netherlands",
      "id": "NL",
      "value": -0.008,
      "extraInfo": false,
      "text_content": "-0.8 percentage points",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Austria",
      "id": "AT",
      "value": 0.045,
      "extraInfo": false,
      "text_content": "+4.5 percentage points",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Poland",
      "id": "PL",
      "value": 0.069,
      "extraInfo": false,
      "text_content": "+6.9 percentage points",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Portugal",
      "id": "PT",
      "value": -0.047,
      "extraInfo": false,
      "text_content": "-4.7 percentage points",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Romania",
      "id": "RO",
      "value": 0.116,
      "extraInfo": false,
      "text_content": "+11.6 percentage points",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Slovenia",
      "id": "SI",
      "value": 0.05,
      "extraInfo": false,
      "text_content": "+5.0 percentage points",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Slovakia",
      "id": "SK",
      "value": 0.107,
      "extraInfo": false,
      "text_content": "+10.7 percentage points",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Finland",
      "id": "FI",
      "value": -0.01,
      "extraInfo": false,
      "text_content": "-1.0 percentage points",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Sweden",
      "id": "SE",
      "value": -0.042,
      "extraInfo": false,
      "text_content": "-4.2 percentage points",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    }
  ],
  "datasetType": "values",
  "datasetUnit": "percent",
  "percentRounded": false,
  "colourSchemeType": "sequential",
  "colourScheme": "red",
  "colourSchemeReverse": false,
  "headlineAvailable": true,
  "subheadlineAvailable": true,
  "tooltipAvailable": true,
  "scaleBarAvailable": true,
  "overrideScaleValues": false,
  "legendAvailable": true,
  "textSourceAvailable": true,
  "textSourceDescription": "Source",
  "textSource": "Eurostat (2026)",
  "textNoteAvailable": true,
  "textNoteDescription": "Note",
  "textNote": "This data women aged between 50 and 69.",
  "textDataAccessAvailable": true,
  "linkDataAccessDescription": "Access the data",
  "linkDataAccess": "https://ec.europa.eu/eurostat/databrowser/view/hlth_ehis_pa7i__custom_22856122/default/table",
  "legend1": "No data available",
  "legend1Color": "#E0E0E0",
  "customUnitLabelAvailable": false,
  "customUnitLabel": "",
  "tooltipExtraInfoLabel": "Click here",
  "translate": {
    "title": "What is the relationship between income and mammography screening in the EU? ",
    "subtitle": "In 2019, women in the EU's highest income bracket were 4.9 percentage points more likely than those in the lowest to report that their last mammogram was one or two years ago.  Bulgaria had the largest positive gap (21.2%), while Croatia had the largest negative gap (-12.5%).",
    "textNoteDescription": "Note",
    "textNote": "This data women aged between 50 and 69.",
    "textSourceDescription": "Source",
    "textSource": "Eurostat (2026)",
    "linkDataAccessDescription": "Access the data",
    "legend1": "No data available",
    "tooltipExtraInfoLabel": "Click here",
    "extraInfo_BE": "-7.6 percentage points",
    "extraInfo_BG": "+21.2 percentage points",
    "extraInfo_CZ": "+6.5 percentage points",
    "extraInfo_DK": "-1.6 percentage points",
    "extraInfo_DE": "+7.6 percentage points",
    "extraInfo_EE": "+5.9 percentage points",
    "extraInfo_IE": "-8.5 percentage points",
    "extraInfo_EL": "-1.7 percentage points",
    "extraInfo_ES": "-2.3 percentage points",
    "extraInfo_FR": "+2.7 percentage points",
    "extraInfo_HR": "-12.5 percentage points",
    "extraInfo_IT": "+5.3 percentage points",
    "extraInfo_CY": "+11.7 percentage points",
    "extraInfo_LV": "+0.8 percentage points",
    "extraInfo_LT": "+9.2 percentage points",
    "extraInfo_LU": "-1.8 percentage points",
    "extraInfo_HU": "+1.9 percentage points",
    "extraInfo_MT": "+0.1 percentage points",
    "extraInfo_NL": "-0.8 percentage points",
    "extraInfo_AT": "+4.5 percentage points",
    "extraInfo_PL": "+6.9 percentage points",
    "extraInfo_PT": "-4.7 percentage points",
    "extraInfo_RO": "+11.6 percentage points",
    "extraInfo_SI": "+5.0 percentage points",
    "extraInfo_SK": "+10.7 percentage points",
    "extraInfo_FI": "-1.0 percentage points",
    "extraInfo_SE": "-4.2 percentage points"
  },
  "clusters": [],
  "colorScale": null,
  "extraInfo_BE": "-7.6 percentage points",
  "extraInfo_BG": "+21.2 percentage points",
  "extraInfo_CZ": "+6.5 percentage points",
  "extraInfo_DK": "-1.6 percentage points",
  "extraInfo_DE": "+7.6 percentage points",
  "extraInfo_EE": "+5.9 percentage points",
  "extraInfo_IE": "-8.5 percentage points",
  "extraInfo_EL": "-1.7 percentage points",
  "extraInfo_ES": "-2.3 percentage points",
  "extraInfo_FR": "+2.7 percentage points",
  "extraInfo_HR": "-12.5 percentage points",
  "extraInfo_IT": "+5.3 percentage points",
  "extraInfo_CY": "+11.7 percentage points",
  "extraInfo_LV": "+0.8 percentage points",
  "extraInfo_LT": "+9.2 percentage points",
  "extraInfo_LU": "-1.8 percentage points",
  "extraInfo_HU": "+1.9 percentage points",
  "extraInfo_MT": "+0.1 percentage points",
  "extraInfo_NL": "-0.8 percentage points",
  "extraInfo_AT": "+4.5 percentage points",
  "extraInfo_PL": "+6.9 percentage points",
  "extraInfo_PT": "-4.7 percentage points",
  "extraInfo_RO": "+11.6 percentage points",
  "extraInfo_SI": "+5.0 percentage points",
  "extraInfo_SK": "+10.7 percentage points",
  "extraInfo_FI": "-1.0 percentage points",
  "extraInfo_SE": "-4.2 percentage points"
});
